channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy=1.21
  - pandas=1.5.0
  - python=3.10.*
  - r-irr
  - rpy2 
  - scikit-learn
  - scipy
  - seaborn
  - sh
  - shap
  - statsmodels
  - tqdm
  - zenodo_get
  - bioconda::snakemake
  - opensim-org::opensim=4.4

