channels:
  - conda-forge
  - opensim-org
  - bioconda
  - defaults
dependencies:
  - ipywidgets=8.1.5
  - jupyterlab=4.2.5
  - matplotlib=3.8.4
  - numpy=1.21.6
  - opensim=4.4
  - pandas=1.5.0
  - python=3.9.19
  - scikit-learn=1.5.2
  - scipy=1.11.2
  - seaborn=0.13.2
  - sh=2.0.7
  - shap=0.42.1
  - snakemake=7.32.4
  - statsmodels=0.14.2
  - tqdm=4.66.5

