name: opensim-nmd
channels:
  - bioconda
  - opensim-org
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - openssl=1.1.1
  - cryptography=39.0.1
  - scipy=1.10.1
  - grpcio
  - kiwisolver=1.4.4
  - aioeasywebdav=2.4.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - amply=0.1.6
  - anyio=4.4.0
  - appdirs=1.4.4
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attmap=0.13.2
  - attrs=24.2.0
  - babel=2.14.0
  - bcrypt=4.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - boto3=1.35.21
  - botocore=1.35.21
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cloudpickle=3.0.0
  - coin-or-cbc=2.10.12
  - coincbc=2.10.12
  - colorama=0.4.6
  - contourpy=1.2.1
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=2.1.0
  - frozenlist=1.4.1
  - google-auth=2.34.0
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyterlab=4.2.5
  - kiwisolver=1.4.4
  - matplotlib=3.8.4
  - numpy=1.21.6
  - opensim=4.4.0
  - pandas=1.5.0
  - python-dateutil=2.9.0
  - pytz=2024.2
  - r-irr=0.84.1
  - rpy2=3.5.11
  - scikit-learn=1.1.1
  - statsmodels=0.14.0
  - seaborn=0.13.2
  - setuptools=73.0.1
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - sh=2.0.7
  - shap-0.42.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - wheel=0.44.0
  - zstd=1.5.6

