channels:
  - conda-forge
  - opensim-org
  - bioconda
  - defaults
dependencies:
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - opensim=4.4
  - pandas=1.5.0
  - python=3.9
  - scikit-learn
  - scipy
  - seaborn
  - sh
  - shap
  - snakemake
  - statsmodels
  - tqdm

