channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - opensim-org::opensim=4.4
  - pandas
  - python=3.9
  - scikit-learn
  - scipy
  - seaborn
  - sh
  - shap
  - bioconda::snakemake
  - statsmodels
  - tqdm

